name: GKE Deployment

on:
  push:
    branches:
      - kube-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
      
    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '331.0.0'
        project_id: devops-kube-4al2
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/devops-kube-4al2/trademe:latest
        
    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials archi-cluster --zone=eu-west2
        
    - name: Deploy API
      run: |
        kubectl apply -f kubernetes/deployment.yml
        kubectl apply -f kubernetes/service.yml
