name: GKE Deployment

on:
  push:
    branches:
      - kube-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
      
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'

    - name: Export gcloud related env variable
      run: export CLOUDSDK_PYTHON="/usr/bin/python3" | export USE_GKE_GCLOUD_AUTH_PLUGIN=True

    - id: 'google-auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'
    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
        
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/devops-kube-4al2/trademe:latest
        
    - name: Install gcloud component auth plugin
      run: gcloud components install gke-gcloud-auth-plugin

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials archi-cluster --zone=europe-west2
        
    - name: Deploy API
      run: |
        kubectl apply -f kubernetes/deployment.yml
        kubectl apply -f kubernetes/service.yml
